package ch.digorydoo.titanium.engine.editor.action

import ch.digorydoo.titanium.engine.brick.Brick
import ch.digorydoo.titanium.engine.brick.BrickShape
import ch.digorydoo.titanium.engine.brick.BrickShape.*
import ch.digorydoo.titanium.engine.core.App
import ch.digorydoo.titanium.engine.editor.Selection

class RotateBricksHandler(private val helper: ActionHelper, private val selection: Selection) {
    fun rotateSelection() {
        val sel = selection.getUnreversed().takeIf { it.xsize > 0 && it.ysize > 0 && it.zsize > 0 } ?: return
        val before = Array(sel.xsize) { Array(sel.ysize) { Array(sel.zsize) { Brick() } } }

        selection.forEachBrick { x, y, z ->
            val ax = x - sel.x0
            val ay = y - sel.y0
            val az = z - sel.z0
            val brick = before[ax][ay][az]
            App.bricks.getAtBrickCoord(x, y, z, brick)
        }

        selection.set(sel.x0, sel.y0, sel.z0, sel.x0 + sel.ysize, sel.y0 + sel.xsize, sel.z0 + sel.zsize)

        helper.applyToAllSelectedBricks { x, y, z, brick ->
            val ax = y - sel.y0
            val ay = (sel.ysize - 1) - (x - sel.x0)
            val az = z - sel.z0
            brick.set(before[ax][ay][az])
            brick.shape = rotate(brick.shape)
            true
        }
    }

    private fun rotate(shape: BrickShape) = when (shape) {
        NONE -> NONE
        BASIC_BLOCK -> BASIC_BLOCK
        BAR_FRAME_NORTH -> BAR_FRAME_WEST
        BAR_FRAME_EAST -> BAR_FRAME_NORTH
        BAR_FRAME_SOUTH -> BAR_FRAME_EAST
        BAR_FRAME_WEST -> BAR_FRAME_SOUTH
        BEVEL_NORTH -> BEVEL_WEST
        BEVEL_EAST -> BEVEL_NORTH
        BEVEL_SOUTH -> BEVEL_EAST
        BEVEL_WEST -> BEVEL_SOUTH
        BEVEL_NN -> BEVEL_WW
        BEVEL_EE -> BEVEL_NN
        BEVEL_SS -> BEVEL_EE
        BEVEL_WW -> BEVEL_SS
        BEVEL_NE -> BEVEL_NW
        BEVEL_NS -> BEVEL_WE
        BEVEL_NW -> BEVEL_SW
        BEVEL_SE -> BEVEL_NE
        BEVEL_SW -> BEVEL_SE
        BEVEL_WE -> BEVEL_NS
        FLAT_CEILING -> FLAT_CEILING
        FLAT_FLOOR -> FLAT_FLOOR
        FLAT_WALL_EAST -> FLAT_WALL_NORTH
        FLAT_WALL_NORTH -> FLAT_WALL_WEST
        FLAT_WALL_SOUTH -> FLAT_WALL_EAST
        FLAT_WALL_WEST -> FLAT_WALL_SOUTH
        HALFD_HIGH_BAR_EAST -> HALFD_HIGH_BAR_NORTH
        HALFD_HIGH_BAR_NORTH -> HALFD_HIGH_BAR_WEST
        HALFD_HIGH_BAR_SOUTH -> HALFD_HIGH_BAR_EAST
        HALFD_HIGH_BAR_WEST -> HALFD_HIGH_BAR_SOUTH
        HALFD_WALL_CORNER_NE -> HALFD_WALL_CORNER_NW
        HALFD_WALL_CORNER_NW -> HALFD_WALL_CORNER_SW
        HALFD_WALL_CORNER_SE -> HALFD_WALL_CORNER_NE
        HALFD_WALL_CORNER_SW -> HALFD_WALL_CORNER_SE
        HALFD_WALL_CORNER_TOP_NE -> HALFD_WALL_CORNER_TOP_NW
        HALFD_WALL_CORNER_TOP_NW -> HALFD_WALL_CORNER_TOP_SW
        HALFD_WALL_CORNER_TOP_SE -> HALFD_WALL_CORNER_TOP_NE
        HALFD_WALL_CORNER_TOP_SW -> HALFD_WALL_CORNER_TOP_SE
        HALFD_WALL_EAST -> HALFD_WALL_NORTH
        HALFD_WALL_NORTH -> HALFD_WALL_WEST
        HALFD_WALL_SOUTH -> HALFD_WALL_EAST
        HALFD_WALL_TOP_EAST -> HALFD_WALL_TOP_NORTH
        HALFD_WALL_TOP_NORTH -> HALFD_WALL_TOP_WEST
        HALFD_WALL_TOP_SOUTH -> HALFD_WALL_TOP_EAST
        HALFD_WALL_TOP_WEST -> HALFD_WALL_TOP_SOUTH
        HALFD_WALL_WEST -> HALFD_WALL_SOUTH
        HALFH_CEILING -> HALFH_CEILING
        HALFH_CEILING_V_CUT_NE -> HALFH_CEILING_V_CUT_NW
        HALFH_CEILING_V_CUT_NW -> HALFH_CEILING_V_CUT_SW
        HALFH_CEILING_V_CUT_SE -> HALFH_CEILING_V_CUT_NE
        HALFH_CEILING_V_CUT_SW -> HALFH_CEILING_V_CUT_SE
        HALFH_FLOOR -> HALFH_FLOOR
        HALFH_FLOOR_V_CUT_NE -> HALFH_FLOOR_V_CUT_NW
        HALFH_FLOOR_V_CUT_NW -> HALFH_FLOOR_V_CUT_SW
        HALFH_FLOOR_V_CUT_SE -> HALFH_FLOOR_V_CUT_NE
        HALFH_FLOOR_V_CUT_SW -> HALFH_FLOOR_V_CUT_SE
        HALF_RAMP_TOP_EAST -> HALF_RAMP_TOP_NORTH
        HALF_RAMP_TOP_NORTH -> HALF_RAMP_TOP_WEST
        HALF_RAMP_TOP_SOUTH -> HALF_RAMP_TOP_EAST
        HALF_RAMP_TOP_WEST -> HALF_RAMP_TOP_SOUTH
        HIGH_BAR_EAST -> HIGH_BAR_NORTH
        HIGH_BAR_NORTH -> HIGH_BAR_WEST
        HIGH_BAR_SOUTH -> HIGH_BAR_EAST
        HIGH_BAR_WEST -> HIGH_BAR_SOUTH
        INVERSE_RAMP_RUN_EAST -> INVERSE_RAMP_RUN_NORTH
        INVERSE_RAMP_RUN_NORTH -> INVERSE_RAMP_RUN_WEST
        INVERSE_RAMP_RUN_SOUTH -> INVERSE_RAMP_RUN_EAST
        INVERSE_RAMP_RUN_WEST -> INVERSE_RAMP_RUN_SOUTH
        LOW_BAR_EAST -> LOW_BAR_NORTH
        LOW_BAR_NORTH -> LOW_BAR_WEST
        LOW_BAR_NS -> LOW_BAR_WE
        LOW_BAR_SOUTH -> LOW_BAR_EAST
        LOW_BAR_WE -> LOW_BAR_NS
        LOW_BAR_WEST -> LOW_BAR_SOUTH
        OCTAGONAL_UPRIGHT_PILLAR -> OCTAGONAL_UPRIGHT_PILLAR
        RAMP_CORNER_NE -> RAMP_CORNER_NW
        RAMP_CORNER_NE_ALT -> RAMP_CORNER_NW_ALT
        RAMP_CORNER_NW -> RAMP_CORNER_SW
        RAMP_CORNER_NW_ALT -> RAMP_CORNER_SW_ALT
        RAMP_CORNER_SE -> RAMP_CORNER_NE
        RAMP_CORNER_SE_ALT -> RAMP_CORNER_NE_ALT
        RAMP_CORNER_SW -> RAMP_CORNER_SE
        RAMP_CORNER_SW_ALT -> RAMP_CORNER_SE_ALT
        RAMP_RUN_EAST -> RAMP_RUN_NORTH
        RAMP_RUN_NORTH -> RAMP_RUN_WEST
        RAMP_RUN_SOUTH -> RAMP_RUN_EAST
        RAMP_RUN_WEST -> RAMP_RUN_SOUTH
        STAIRS_RUN_EAST -> STAIRS_RUN_NORTH
        STAIRS_RUN_NORTH -> STAIRS_RUN_WEST
        STAIRS_RUN_SOUTH -> STAIRS_RUN_EAST
        STAIRS_RUN_WEST -> STAIRS_RUN_SOUTH
        STRAIGHT_STAIRS_EAST -> STRAIGHT_STAIRS_NORTH
        STRAIGHT_STAIRS_NORTH -> STRAIGHT_STAIRS_WEST
        STRAIGHT_STAIRS_SOUTH -> STRAIGHT_STAIRS_EAST
        STRAIGHT_STAIRS_WEST -> STRAIGHT_STAIRS_SOUTH
        THICK_CEILING -> THICK_CEILING
        THICK_CEILING_V_CUT_NE -> THICK_CEILING_V_CUT_NW
        THICK_CEILING_V_CUT_NW -> THICK_CEILING_V_CUT_SW
        THICK_CEILING_V_CUT_SE -> THICK_CEILING_V_CUT_NE
        THICK_CEILING_V_CUT_SW -> THICK_CEILING_V_CUT_SE
        THICK_FLOOR -> THICK_FLOOR
        THICK_FLOOR_V_CUT_NE -> THICK_FLOOR_V_CUT_NW
        THICK_FLOOR_V_CUT_NW -> THICK_FLOOR_V_CUT_SW
        THICK_FLOOR_V_CUT_SE -> THICK_FLOOR_V_CUT_NE
        THICK_FLOOR_V_CUT_SW -> THICK_FLOOR_V_CUT_SE
        THICK_HALFH_HIGH_BAR_EAST -> THICK_HALFH_HIGH_BAR_NORTH
        THICK_HALFH_HIGH_BAR_NORTH -> THICK_HALFH_HIGH_BAR_WEST
        THICK_HALFH_HIGH_BAR_SOUTH -> THICK_HALFH_HIGH_BAR_EAST
        THICK_HALFH_HIGH_BAR_WEST -> THICK_HALFH_HIGH_BAR_SOUTH
        THICK_HALFH_LOW_BAR_EAST -> THICK_HALFH_LOW_BAR_NORTH
        THICK_HALFH_LOW_BAR_NORTH -> THICK_HALFH_LOW_BAR_WEST
        THICK_HALFH_LOW_BAR_SOUTH -> THICK_HALFH_LOW_BAR_EAST
        THICK_HALFH_LOW_BAR_WEST -> THICK_HALFH_LOW_BAR_SOUTH
        THICK_HIGH_BAR_NORTH -> THICK_HIGH_BAR_WEST
        THICK_HIGH_BAR_WEST -> THICK_HIGH_BAR_SOUTH
        THICK_HIGH_BAR_SOUTH -> THICK_HIGH_BAR_EAST
        THICK_HIGH_BAR_EAST -> THICK_HIGH_BAR_NORTH
        THICK_WALL_CORNER_NE -> THICK_WALL_CORNER_NW
        THICK_WALL_CORNER_NW -> THICK_WALL_CORNER_SW
        THICK_WALL_CORNER_SE -> THICK_WALL_CORNER_NE
        THICK_WALL_CORNER_SW -> THICK_WALL_CORNER_SE
        THICK_WALL_CORNER_TOP_NE -> THICK_WALL_CORNER_TOP_NW
        THICK_WALL_CORNER_TOP_NW -> THICK_WALL_CORNER_TOP_SW
        THICK_WALL_CORNER_TOP_SE -> THICK_WALL_CORNER_TOP_NE
        THICK_WALL_CORNER_TOP_SW -> THICK_WALL_CORNER_TOP_SE
        THICK_WALL_EAST -> THICK_WALL_NORTH
        THICK_WALL_NORTH -> THICK_WALL_WEST
        THICK_WALL_SOUTH -> THICK_WALL_EAST
        THICK_WALL_TOP_EAST -> THICK_WALL_TOP_NORTH
        THICK_WALL_TOP_NORTH -> THICK_WALL_TOP_WEST
        THICK_WALL_TOP_SOUTH -> THICK_WALL_TOP_EAST
        THICK_WALL_TOP_WEST -> THICK_WALL_TOP_SOUTH
        THICK_WALL_WEST -> THICK_WALL_SOUTH
        THIN_WALL_CORNER_NE -> THIN_WALL_CORNER_NW
        THIN_WALL_CORNER_NW -> THIN_WALL_CORNER_SW
        THIN_WALL_CORNER_SE -> THIN_WALL_CORNER_NE
        THIN_WALL_CORNER_SW -> THIN_WALL_CORNER_SE
        THIN_WALL_CORNER_TOP_NE -> THIN_WALL_CORNER_TOP_NW
        THIN_WALL_CORNER_TOP_NW -> THIN_WALL_CORNER_TOP_SW
        THIN_WALL_CORNER_TOP_SE -> THIN_WALL_CORNER_TOP_NE
        THIN_WALL_CORNER_TOP_SW -> THIN_WALL_CORNER_TOP_SE
        THIN_WALL_DIAGONAL_NE -> THIN_WALL_DIAGONAL_NW
        THIN_WALL_DIAGONAL_NW -> THIN_WALL_DIAGONAL_SW
        THIN_WALL_DIAGONAL_SE -> THIN_WALL_DIAGONAL_NE
        THIN_WALL_DIAGONAL_SW -> THIN_WALL_DIAGONAL_SE
        THIN_WALL_EAST -> THIN_WALL_NORTH
        THIN_WALL_NORTH -> THIN_WALL_WEST
        THIN_WALL_SOUTH -> THIN_WALL_EAST
        THIN_WALL_TOP_EAST -> THIN_WALL_TOP_NORTH
        THIN_WALL_TOP_NORTH -> THIN_WALL_TOP_WEST
        THIN_WALL_TOP_SOUTH -> THIN_WALL_TOP_EAST
        THIN_WALL_TOP_WEST -> THIN_WALL_TOP_SOUTH
        THIN_WALL_WEST -> THIN_WALL_SOUTH
        UPRIGHT_BAR_NE -> UPRIGHT_BAR_NW
        UPRIGHT_BAR_NW -> UPRIGHT_BAR_SW
        UPRIGHT_BAR_SE -> UPRIGHT_BAR_NE
        UPRIGHT_BAR_SW -> UPRIGHT_BAR_SE
        UPRIGHT_DBL_BAR_EAST -> UPRIGHT_DBL_BAR_NORTH
        UPRIGHT_DBL_BAR_NORTH -> UPRIGHT_DBL_BAR_WEST
        UPRIGHT_DBL_BAR_SOUTH -> UPRIGHT_DBL_BAR_EAST
        UPRIGHT_DBL_BAR_WEST -> UPRIGHT_DBL_BAR_SOUTH
        VERTICAL_BEVEL_FULL -> VERTICAL_BEVEL_FULL
        VERTICAL_BEVEL_FULL_ALT -> VERTICAL_BEVEL_FULL_ALT
        VERTICAL_BEVEL_EAST -> VERTICAL_BEVEL_NORTH
        VERTICAL_BEVEL_NE -> VERTICAL_BEVEL_NW
        VERTICAL_BEVEL_NORTH -> VERTICAL_BEVEL_WEST
        VERTICAL_BEVEL_NW -> VERTICAL_BEVEL_SW
        VERTICAL_BEVEL_SE -> VERTICAL_BEVEL_NE
        VERTICAL_BEVEL_SOUTH -> VERTICAL_BEVEL_EAST
        VERTICAL_BEVEL_SW -> VERTICAL_BEVEL_SE
        VERTICAL_BEVEL_WEST -> VERTICAL_BEVEL_SOUTH
        VERTICAL_CUT_NE -> VERTICAL_CUT_NW
        VERTICAL_CUT_NW -> VERTICAL_CUT_SW
        VERTICAL_CUT_SE -> VERTICAL_CUT_NE
        VERTICAL_CUT_SW -> VERTICAL_CUT_SE
        WINDING_STAIRS_EN -> WINDING_STAIRS_NW
        WINDING_STAIRS_ES -> WINDING_STAIRS_NE
        WINDING_STAIRS_LOWER_EN -> WINDING_STAIRS_LOWER_NW
        WINDING_STAIRS_LOWER_ES -> WINDING_STAIRS_LOWER_NE
        WINDING_STAIRS_LOWER_NE -> WINDING_STAIRS_LOWER_WN
        WINDING_STAIRS_LOWER_NW -> WINDING_STAIRS_LOWER_WS
        WINDING_STAIRS_LOWER_SE -> WINDING_STAIRS_LOWER_EN
        WINDING_STAIRS_LOWER_SW -> WINDING_STAIRS_LOWER_ES
        WINDING_STAIRS_LOWER_WN -> WINDING_STAIRS_LOWER_SW
        WINDING_STAIRS_LOWER_WS -> WINDING_STAIRS_LOWER_SE
        WINDING_STAIRS_NE -> WINDING_STAIRS_WN
        WINDING_STAIRS_NW -> WINDING_STAIRS_WS
        WINDING_STAIRS_SE -> WINDING_STAIRS_EN
        WINDING_STAIRS_SW -> WINDING_STAIRS_ES
        WINDING_STAIRS_UPPER_EN -> WINDING_STAIRS_UPPER_NW
        WINDING_STAIRS_UPPER_ES -> WINDING_STAIRS_UPPER_NE
        WINDING_STAIRS_UPPER_NE -> WINDING_STAIRS_UPPER_WN
        WINDING_STAIRS_UPPER_NW -> WINDING_STAIRS_UPPER_WS
        WINDING_STAIRS_UPPER_SE -> WINDING_STAIRS_UPPER_EN
        WINDING_STAIRS_UPPER_SW -> WINDING_STAIRS_UPPER_ES
        WINDING_STAIRS_UPPER_WN -> WINDING_STAIRS_UPPER_SW
        WINDING_STAIRS_UPPER_WS -> WINDING_STAIRS_UPPER_SE
        WINDING_STAIRS_WN -> WINDING_STAIRS_SW
        WINDING_STAIRS_WS -> WINDING_STAIRS_SE
        WINDOW_TOP_L_NORTH -> WINDOW_TOP_L_WEST
        WINDOW_TOP_L_EAST -> WINDOW_TOP_L_NORTH
        WINDOW_TOP_L_SOUTH -> WINDOW_TOP_L_EAST
        WINDOW_TOP_L_WEST -> WINDOW_TOP_L_SOUTH
        WINDOW_TOP_R_NORTH -> WINDOW_TOP_R_WEST
        WINDOW_TOP_R_EAST -> WINDOW_TOP_R_NORTH
        WINDOW_TOP_R_SOUTH -> WINDOW_TOP_R_EAST
        WINDOW_TOP_R_WEST -> WINDOW_TOP_R_SOUTH
    }
}
