plugins {
    alias(libs.plugins.kotlin.jvm)
    `java-library`
}

kotlin {
    jvmToolchain(libs.versions.targetJDK.get().toInt())
}

sourceSets {
    main {
        // Add sources generated by GenerateBuildConfigTask
        java.srcDir(rootProject.layout.buildDirectory.dir("generated/build_config"))
    }
}

dependencies {
    // NOTE: versions are now maintained in gradle/libs.versions.toml
    implementation(platform(libs.kotlin.bom))
    testImplementation(libs.kotlin.test)

    implementation(libs.kotlinx.coroutines)
    implementation(libs.kstruct)

    implementation(project(":kutils"))
}
